- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-233
> ESC-233 bug fix

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SignOutController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/Undertaking.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BusinessEntityRemoveYourselfPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ExistingUndertakingPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/RemoveBusinessPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/SignOutPage.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AuthAndSessionDataBehaviour.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala
- test/utils/CommonTestData.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-296
> Esc 296 already have undertaking

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoBusinessPresentController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/Undertaking.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BusinessEntityJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/NewLeadJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AccountPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BusinessEntityRemoveYourselfPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadEORIChangedPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NoBusinessPresentPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NoClaimNotificationPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/SelectNewLeadPage.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoBusinessPresentControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala
- test/utils/CommonTestData.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-295
> Esc 295 promote other be as lead

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/util/ReportDeMinimisReminderHelper.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AccountPage.scala.html
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/util/ReportDeMinimisReminderHelperSpec.scala
ticket detauks -> https://jira.tools.tax.service.gov.uk/browse/ESC-314
> ESC-314 90 days message

- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/SendEmailConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/Language.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailParameters.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailSendRequest.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailSendResult.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SendEmailService.scala
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/SendEmailConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/RetrieveEmailSupport.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SendEmailSupport.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/service/SendEmailServiceSpec.scala
- test/utils/CommonTestData.scala
This was reviewed earlier as well but it was in different branch. I though rebasing will be much more difficult than creating a separate branch and inserting the email changes. So here it is, the new PR for email sending stuff. This PR is to send email when an undertaking is created.
> ESC-217 email send when undertakign is created

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/util/TemplateHelpers.scala
- conf/application.conf
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/service/SendEmailServiceSpec.scala
Pr to send an email to both Lead and business entity in when a BUsiness entity is added to an undertaking
> Esc 218 219 add member

- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BecomeLeadJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BusinessEntityJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/NewLeadJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourneySpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/JourneySpec.scala
- test/utils/CommonTestData.scala
* replace static URI strings on FormPages with lookups on `routes`
* simplify Journey methods, add tests and remove dead code
* switch journey steps from List to Array for index based lookups
* other minor tidy ups
> Esc 344 rebased

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-370
> ESC-370 test cases

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/UndertakingNamePage.scala.html
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
ticket details -> [https://jira.tools.tax.service.gov.uk/browse/ESC-382](https://jira.tools.tax.service.gov.uk/browse/ESC-382)
> ESC-382 back link for undertaking name

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-432
> ESC-432 remove  admin link from lead account page

- conf/messages
* minor copy fixes spotted during the walkthrough session
> NOJIRA minor copy changes from walkthrough session

- app/uk/gov/hmrc/eusubsidycompliancefrontend/config/AppConfig.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SignOutController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/FullWidthLayout.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/IncorrectEoriPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/Layout.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
- conf/application.conf
redirect to feedback service when user click on sign out link
> Esc 33 exit survey

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala
- test/utils/CommonTestData.scala
This Pr is to add undertaking reference to those audit events where it was missing.
> ESC-46 add ref for audit events

- README.md
- conf/app.routes
- conf/application.conf
- conf/prod.routes
PR to change the urls as per the documentation -> https://jira.tools.tax.service.gov.uk/browse/ESC-406
> Esc 405 urls

- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala
Tint PR to rename undertakingIdentifier to underakingReference in some of the audit events
> ESC-462- rename identifier to Untertaking Reference

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/CheckEoriPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/CustomsWaiversPage.scala.html
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourneySpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-481
"Do you, or any business in your organisation, claim Customs Duty waivers?" is no longer the first page, the Eori check page is the first page of the service now.
- Changed the position of the pages in the journey
- Added previous to Customs Duty waivers
- Remove previous from EORi check page,
- Added test cases for both pages
> Esc 481 move page

- build.sbt
* configure coverage threshold of 90% now that test coverage exceeds 90%
> NOJIRA set coverage threshold to 90% now coverage exceeds 90%

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/CreateUndertakingPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/EligibilityTermsAndConditionsPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala
ticket details -> 
https://jira.tools.tax.service.gov.uk/browse/ESC-482
https://jira.tools.tax.service.gov.uk/browse/ESC-483
Change in content in get terms and condition page an create undertaking page
test cases
> ESC-482-83 cotent change

- conf/messages
* updated copy for the 'eori must be in undertaking' validation error on subsidy journey
> ESC-307 update eori in undertaking validation error message

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimDatePage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ReportPaymentPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-492
https://jira.tools.tax.service.gov.uk/browse/ESC-493
- Content change on report payment screen
- Added radio buttons on report payment screen, click on yes continue the journey, No redirect to Home account page
-added hint to subsidy claim date page
> Esc 492 493

- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-494
https://jira.tools.tax.service.gov.uk/browse/ESC-495
> ESC-494-495

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/FinancialDashboardPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/UndertakingCheckYourAnswersPage.scala.html
- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-486
https://jira.tools.tax.service.gov.uk/browse/ESC-501
> ESC-486-501 content change

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BusinessEntityRemoveYourselfPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/RemoveBusinessPage.scala.html
- conf/messages
missed this page as a part of the changes for this ticket https://jira.tools.tax.service.gov.uk/browse/ESC-507
remove business entity page has missing EOri number in the subtitle
> ESC-504-507 bug

- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-508
> ESC-508 content change

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AmendUndertakingPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ClaimCheckYourAnswerPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/SelectNewLeadPage.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-500
https://jira.tools.tax.service.gov.uk/browse/ESC-503
https://jira.tools.tax.service.gov.uk/browse/ESC-498
> ESC-510- call to action button changes

- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-524
> ESC-524 content change

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/FinancialDashboardPage.scala.html
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummarySpec.scala
* fix display of de minimis aid total in financial dashboard
* revise test data and update tests
> ESC-533 update financial dashboard template to show correct value for de minimis aid and update test data

- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/RetrieveEmailConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/SendEmailConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/AuditService.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/JourneyTraverseService.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/RetrieveEmailConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/SendEmailConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/AuditServiceSpec.scala
* remove traits where there is only one implementing class
* revised tests where necessary
> ESC-380 remove traits with only one implementing class

- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-418. (Pls look at the comments)
> ESC-418 content change

- it/uk/gov/hmrc/eusubsidycompliancefrontend/services/JourneyStoreSpec.scala
* added integration tests for JourneyStore
> ESC-582 integration tests for JourneyStore

- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala
- disable undertaking removed as no longer needed.
- removeMember to disable a undertaking and test cases
> Esc 371 disable

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimAmountPage.scala.html
- conf/messages
ticket details -> copy changes are under the comment section of https://jira.tools.tax.service.gov.uk/browse/ESC-597
> ESC-597 change the copy for payment screen

- conf/messages
Missed full stop at the end of each list item earlier 🤦‍♀️
> ESC-597 full stop missing

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmationPage.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
Roll back the changes where the undertaking created success page location was moved.
> ESC-roll back changes

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
Reverts hmrc/eu-subsidy-compliance-frontend#225
> Revert "ESC-612 hide disable undertaking link until feature is ready to go"

- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EmailVerificationServiceSpec.scala
Also switched to using futureValue instead of Await.
> ESC-676 fix test failures by waiting for futures to complete before checking results

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/InputEmailPage.scala.html
- conf/messages
> Update content for email capture when no verified cds email

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidies.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NoClaimConfirmationPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NoClaimNotificationPage.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidiesSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
* revisions to the nil return flow which now includes a new confirmation page for submission of a nil return
* some minor refactoring and tidying up
> ESC-703 Nil Return Journey Changes

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/NonHmrcSubsidy.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidies.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidiesSpec.scala
* sort reported payments by allocation date
* simplify `lastSubmitted`
> ESC-743 ensure reported payments are displayed by descending allocation date

- app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimAmountFormProvider.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimAmountFormProviderSpec.scala
* revised the subsidy amount form validation to delegate to the `PositiveSubsidyAmount` in order to determine if the supplied value is valid or not
* test updates
> ESC-736 fix subsidy amount validation bug

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BecomeAdminConfirmationPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BecomeAdminPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmEmailPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/helpers/P.scala.html
- conf/messages
Summary
* add in frontend commit that was missed from the original ESC-710 merge
> ESC-710 content & accessibility changes to become administrator journey

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProvider.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/FormValues.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/OptionalClaimEori.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/Undertaking.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/types/package.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BusinessEntityJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimBusinessPage.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProviderSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourneySpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
* revised the subisdy journey to allow an EORI that's not part of any undertaking to be added during the flow
* some refactoring including simplifying the next/previous methods in SubsidyJourney
* revised and added tests where necessary
> ESC-748 allow business to be added during create subsidy flow

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimBusinessPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ReportedPaymentsPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
* revised the reported payments page so a success banner is shown when a payment is removed
* updated tests to cover this and verify that the banner is shown
> ESC-801 show success banner when removing a payment

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BaseController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
* provide a helper method on `BaseController` to handle the run if step is eligible otherwise redirect to the previous step logic
* update controllers to use this where applicable
> ESC-839 extract is eligible for step logic into function

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummary.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummarySpec.scala
> ESC-971 sector allowance

- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/types/package.scala
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/ESC-896
> change error hint message and update character limit spaces

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimDatePage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmEmailPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/helpers/H1.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
Both tickets implemented in one PR as a pragmatic approach.
- ESC-887 add visually hidden email address in question
- ESC-889 updated error messages and error highlighting for add claim date page
> ESC-887 & ESC-889 addressed DAC issues

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimAmountPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimDatePage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmEmailPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- ESC-1034 updated confirm email page question
- ESC-1043 updated content on add claim date page
- ESC-1058 updated content on add payment amount page
> ESC-1034, ESC-1043 & ESC-1058 fixed DAC issues

- app/uk/gov/hmrc/eusubsidycompliancefrontend/config/AppConfig.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/models/types/package.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BusinessEntityEoriPage.scala.html
- conf/application.conf
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/XIDisableBusinessControllerSpec.scala
- update content and add feature flag for XI EORI removal
> ESC-1136 - update content and add feature flag for XI EORI removal

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/CheckEoriPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/XIEligibilityControllerSpec.scala
XI EORI Updates with feature flag
> ESC-1250 - XI EORI Updates with feature flag

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimAmountPage.scala.html
Removing comma from AddClaimAmountPage view.
> DDCYLS-5414 Eu Subs FE - remove comma from AddClaimAmountPage view

- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/Connector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/CustomsDataStoreConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EmailConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EmailVerificationConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/SendEmailConnector.scala
- conf/application.conf
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/CustomsDataStoreConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EmailVerificationConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/HttpSupport.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/SendEmailConnectorSpec.scala
Dependency upgrades for EU Subs Frontend.
> DDCYLS:6426 - Dependency upgrades 

- README.md
- project/AppDependencies.scala
> DDCYLS - 6375 - Updating Readme Content

- precheck.sh
> DDCYLS-6654: added precheck

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
> DDCYLS-6950: dependency upgrades

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NonLeadAccountPage.scala.html
- conf/messages
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
updated the content and test cases as per the jira story
> DDCYLS-6804: updated the content as per the jira story

- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/LeadAccountPage.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/NonLeadAccountPage.scala.html
- conf/messages
Accommodating the review comments
> DDCYLS-6804: Accommodating the review comments

- conf/application.conf
- test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
- test/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummarySpec.scala
DDCYLS-7141: changing sector cap from 20000 to 50000
> DDCYLS-7141: changing sector cap from 20000 to 50000

- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ConstructionController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NACELvlOneController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/journeys/UndertakingJourney.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/navigation/Navigator.scala
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/nace/construction/CivilEngineeringLvl3Page.scala.html
- app/uk/gov/hmrc/eusubsidycompliancefrontend/views/nace/lvl1/GeneralTradeUndertakingPage.scala.html
- conf/app.routes
> POC - for navigation.
