app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AccountPage.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AmendUndertakingPage.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/service/EscServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/testutil/FakeTimeProvider.scala, test/utils/CommonTestData.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-263
The attached image in the ticket has four fields in the amend undertaking screen but that is old, now we have only three
undertaking name, sector and contact.
I have added a new link called amen-undertaking details, which is the new screen where user can edit the details already entered.
I have created a new isAmend flag, which take care of the previous and next pages. Since we are reusing the same pages we had while creating undertaking, this time we check the isAmend flag. If yes then the previous and next of the pages is amend screen details only.
There is some code refactoring as well with test cases(only for those controllers methods which are used in this ticket)
=> Esc 263 amend undertaking

app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ReportPaymentPage.scala.html
This fixes the rendering of optional values and also ensures we show the trader reference instead of the transaction ID.
=> ESC-315-further-fixes fix rendering of subsidy values

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-305
There was this bug on the add claim eori page and  trader ref page on subsidy payment journey where the option selected by user were not getting retained if user clicks on back link or change link on cya page.
I accidentally pushed the code to main branch 🤦‍♀️ , so I have added comments at the parts which were changed as a part of bug fix. I have done some changes and added unit test cases for those changes.
=> Esc 305 bug testcase

build.sbt
This can cause issues with Junit XML output getting mangled causing
unstable builds in Jenkins.
See https://github.com/scalatest/scalatest/issues/1427
=> NOJIRA disable duplicate junit reporter

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
* when the user reaches the check your answers page they can click on change links for name, sector and contact to jump back and edit
* when the form is submitted and if they have already provided answers for name, sector and contact, they are redirected back to the check your answers page, rather than having to follow the remaining create undertaking flow
* removed `getNextJourney` method in Controller and replaced this with the `next` method on the journey, to better encapsulate the journey logic
=> ESC-332 - change value flow when editing individual values for create undertaking 

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpers.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearSyntax.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimDatePage.scala.html, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/RetrieveEmailServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/SendEmailServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpersSpec.scala
* moved logic that calculates the earliest allowed date into `TaxYearHelpers` and provided an extension method 
* refactored date validation removing boilerplate and grouping the validation checks into logical groups
* revised the validation error rendering to support arbitrary args allowing dates to be passed for those error messages that need to show dynamic date values
* other refactors and tidying including correcting the package on some tests
=> ESC-318 Dynamic dates on date validation error messages

app/uk/gov/hmrc/eusubsidycompliancefrontend/config/AppConfig.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SendEmailHelperService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/util/EmailTemplateHelpers.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/BecomeAdminConfirmatinPage.scala.html, conf/application.conf, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala, test/utils/CommonTestData.scala
- Email when a business entity promote themself as lead , it should send email to both new lead and old lead.
- Did some refactoring. All the email stuff - getting params, template id, language code is now under SendEmailHelperService
=> Esc 227 228 lead removed email

app/uk/gov/hmrc/eusubsidycompliancefrontend/models/Undertaking.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BecomeLeadJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BusinessEntityJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/NewLeadJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EligibilityJourneySpec.scala, test/utils/CommonTestData.scala
* revised the form type to make the URL a def so that it's not serialized and stored in mongo DB
* introduced a concrete class for each form and updated the journeys and associated test code
* removed unused implicits
* other minor tidy ups
Note - there will be a PR after this to clean up the URLs and take them from the routes reverse lookup instead of using hardcoded strings.
=> ESC-344 Do not store form URLs in MongoDB

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, conf/app.routes, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala, test/utils/CommonTestData.scala
ticket details ->  audit events json as mentioned here [link](https://confluence.tools.tax.service.gov.uk/display/CIP/EU+Subsidy+Compliance+-+Transaction+Monitoring+Assessment)
It includes audit events for Non HMRC subsidy addition, remove, update and nil submission.
some code refactor and test cases included
=> Esc 364 65 66 67 68 subsidy journey audit events

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/RetrieveEmailConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UpdateEmailAddressController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailType.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/RetrieveEmailResponse.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/RetrieveEmailService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SendEmailHelperService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/UpdateUndeliveredEmailAddressPage.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/UpdateUnverifiedEmailPage.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/RetrieveEmailSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/RetrieveEmailServiceSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-251
- When user logs in  and if the email address associated to EORI is not registered with CDS or unverified, then user is redirected to kickout page stating the email address is Unverified.
- if the email address is undeliverable, then user is redirected Undelivered kick out page  
- unit test cases for above scenario, some unit test cases formatting.
=> Esc 392 393 no unverified email

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala
ticket details -> [here](https://jira.tools.tax.service.gov.uk/browse/ESC-397)
- add audit event for the process when a business entity delete itself
=> ESC-397 BE remove itself audit event and test case

app/uk/gov/hmrc/eusubsidycompliancefrontend/services/UndertakingJourney.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-385
the back link on CYA page was not working because in the previous logic it was going to second else which says 
`else if (requiredDetailsProvided) routes.UndertakingController.getCheckAnswers().url`
but it should not go there if the current page is CYA page , so added the check there `&& !isCurrentPageCYA`
=> Esc 385 cya page

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/json/eis/ResponseCommon.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala
This PR is to fix a bug when a EORi is entered on add member page. As of now , the backend only handles the exception when the error code is 107 but do not handle if the error code is 055. In case of error 055, the FE should display a form error and says `Enter a valid EORI`. This message is still not confirmed so as of now it' decided to use this message as this EORI is not valid to be used . 
- Change in STUB-> added a scenario where a EORI ending with 777 will give 055 error code.
- Change in BE-> handled the code as 406 cause 404 means not found and not found scenario is handled differently in FE.
- change in FE-  Created a new function  retrieveUndertakingWithErrorResponse which check the response status , if 406, then , parse the response for UpstreamErrorResponse and if it's parsed …
=> Esc 414 eori validate for add

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
* add lead eori check to the amend undertaking get and post handlers
* update tests to expect additional calls to the store to retrieve the undertaking
=> ESC-383 add lead eori restriction to amend undertaking get and post handlers

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/ConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala
* the undertaking retrieval code in the connector has been revised to return a Right on HTTP 200, and a Left on all other responses
* revised the ESC service to take appropriate action depending on whether a Left or Right is returned by the connector
* updated tests to account for this change 
Note - this fixes an issue where an error connecting to EIS would be interpreted as 'no undertaking present' by the frontend.
=> ESC-528 Revise error handling on undertaking retrieval in connector

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/Connector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/RetrieveEmailConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/SendEmailConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/SubsidyUpdate.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/BusinessEntityJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/ConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala
* introduced `Connector` trait that provides a `makeRequest` method that provides common response handling for all connector calls
* revised the logic so any 2xx response results in a Right(...) with any other status code result in a Left(...)
* updated connectors to use `makeRequest` and updated the tests
* added coverage for the `removeSubsidy` method of the ESC Connector
* removed dead code
=> ESC-532 introduce common response handling for connectors

app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProvider.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProviderSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-550
The bug for date occurred because the user entered 09 in the month and the data was saved like  this in the journey.
since we don't have any value for date.09 inn the messages conf file. It appeared as it is in the Form.
-This PR is for  fixing this bug where now code trims the prefixed 0 in date and month place entered by user. 
-Plus the error message , which says "Enter the date you were awarded the payment. Date must be 06 04 2021, or later." the prefixed 0 from the day and month has been removed as per discussion with Dan. So it should be like this "Enter the date you were awarded the payment. Date must be 6 4 2021, or later."
=> Esc 550 fix date

conf/application.conf
* increase request timeouts from default of 20s to 60s
=> ESC-560 increase request timeouts to 60s

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/LeadOnlyUndertakingSupport.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoBusinessPresentController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/LeadOnlyRedirectSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/LeadOnlyUndertakingSupportSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoBusinessPresentControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
* removed support for caching of Undertaking ahead of work to reimplement this using a dedicated collection keyed on undertaking ID
=> ESC-561 temporarily remove undertaking caching 

app/uk/gov/hmrc/eusubsidycompliancefrontend/cache/UndertakingCache.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/JourneyStore.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Store.scala, it/uk/gov/hmrc/eusubsidycompliancefrontend/cache/UndertakingCacheSpec.scala, project/AppDependencies.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/JourneyStoreSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
* responsibility for Undertaking and UndertakingSubsidies caching delegated to the ESC Service removing caching logic from controllers
* introduced `UndertakingCache` which caches Undertaking and UndertakingSubsidies with `it` test
* cached data invalidated for all users on update
* revised tests and removed dead code
* other minor tidy ups
=> ESC-562 Move undertaking and subsidy caching into ESC Service

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadController.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala
* when a user promotes themselves to lead flush any stale `UndertakingJourney` data from the store to fix a bug where old data could be shown on the edit undertaking screen
=> ESC-583 flush stale UndertakingJourney data when user promotes self to lead

app/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpers.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AuthAndSessionDataBehaviour.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SignOutControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpersSpec.scala
* earliest allowed date logic now updated to enforce the earliest allowed date of `2021-01-01` a constraint currently imposted by ETMP
* updated tests and added explicit tests to cover this logic
* fixed compiler warnings
=> ESC-590 enforce earliest allowed claim date of 2021-01-01 to align with ETMP

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailSendResult.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/RetrieveEmailService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SendEmailHelperService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/EmailNotVerifiedForLeadPromotionPage.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-355
ticket to create a new kickout page , if the business entity member to be promoted don't have a verified email address. 
A similar ticket is coming up for adding/removing BE member
- test cases
Raising PR to get the comments will not merge it till Carwyn's  changes are confirmed
=> Esc 355 kickout page for no email

app/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpers.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AuthAndSessionDataBehaviour.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/FinancialDashboardControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SignOutControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/util/TaxYearHelpersSpec.scala
Reverts hmrc/eu-subsidy-compliance-frontend#208
Reverting the fix to only allow subsidies from 2021-01-01 to be reported since the missing data will now be added.
=> Revert "ESC-590 enforce earliest allowed claim date of 2021-01-01 to align with ETMP"

app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/UndertakingDisabledPage.scala.html, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
This PR include:
- revert the disable undertaking code to call update undertaking API instead of amend undertaking member api 
- change test case for that
- Change the last page of disabled undertaking as per the ticket https://jira.tools.tax.service.gov.uk/browse/ESC-604
=> Esc revert disable changes

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailParameters.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala
* if user navigates directly to the eori check page then ensure EligibilityJourney data is present to allow the user to continue with the first login journey
* minor tidy ups and test changes
=> ESC-611 ensure EligibilityJourney is present if user redirected to eori check page from ECC

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailTemplate.scala, conf/application.conf, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
* added config for disable undertaking lead and business entity templates
* revised the disable undertaking handling to also send emails to the undertaking lead and any business entitites 
* updated tests
=> ESC-593 send emails when undertaking disabled

app/uk/gov/hmrc/eusubsidycompliancefrontend/cache/ExchangeRateCache.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/cache/Helpers.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/cache/UndertakingCache.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/connectors/EscConnector.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ExchangeRateTestController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/ExchangeRate.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscService.scala, conf/app.routes, it/uk/gov/hmrc/eusubsidycompliancefrontend/cache/ExchangeRateCacheSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/cache/YearAndMonthSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/cache/YearAndMonthTest.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/connector/EscConnectorSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/EscServiceSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala
* added connector to fetch exchange rates from ESC backend (which fetches the data from the Europa API)
* added service with caching to handle caching of exchange rates transparently
* added test endpoint to allow testing of the end to end flow before the frontend is built
=> ESC-619 fetch exchange rates from ESC backend

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimAmountFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/FormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/ClaimAmount.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/ExchangeRate.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/audit/AuditEvent.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/types/package.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/Journey.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/JourneyTraverseService.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourney.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/AddClaimAmountPage.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmClaimAmountConversionToEuros.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmationPage.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/formatters/BigDecimalFormatter.scala, conf/app.routes, conf/messages, it/uk/gov/hmrc/eusubsidycompliancefrontend/cache/ExchangeRateCacheSpec.scala, project/AppDependencies.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EscServiceSupport.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimAmountFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/services/SubsidyJourneySpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/test/CommonTestData.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/views/formatters/BigDecimalFormatterSoec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/views/formatters/BigDecimalFormatterSpec.scala
* revised the claim amount page to allow entry of GBP or EUR amounts
* if a GBP amount is entered the user is taken to a new page which converts the amount into Euros and confirms the Euro amount
* extracted claim amount form into a separate form provider class allowing the validation rules to be tested in isolation
* revised the next/previous logic fixing an existing bug and ensuring that the journey flows correctly on the create and amend journeys for both the EUR and GBP flows
* other minor tidy ups including introducing an enum for the currency code
=> ESC-621 allow entry of GBP amounts with new conversion confirmation page

conf/prod.routes
* add new prod routes entry for the new url prefix `report-and-manage-your-allowance-for-customs-duty-waiver-claims`
* retain existing route for compatibility - this can be removed once all references have been replaced with the new prefix
=> ESC-642 add new url prefix along side that currently live to avoid breakage

app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/FormProvider.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProviderSpec.scala
* the radio button code from the HMRC libraries already provides a check to ensure a value is selected so we don't need our own code to do this
*  removed the `radioButtonSelected` method from the `FormProvider` trait and updated the tests
=> ESC-660 simplify form provider trait removing duplicate functionality

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
* when recording a subsidy we delete the subsidy journey state instead of replacing what's there with an empty instance
* if the user hits back from the payment confirmation page we redirect them to the account home page
* updated tests to cover this
=> ESC-734 redirect to account home if no subsidy data found on get cya page

app/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummary.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/views/models/FinancialDashboardSummarySpec.scala
* filter removed subsidy payments from the data when generating the data for the summary page
* updated tests to cover this case
* fixed an unused import warning in one of the tests
=> ESC-821 exclude removed payments when generating summary data

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BusinessEntityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/ControllerFormHelpers.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EmailVerificationSupport.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoBusinessPresentController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimAmountFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimDateFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/EmailFormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/FormHelpers.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/forms/FormProvider.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmEmailPage.scala.html, app/uk/gov/hmrc/eusubsidycompliancefrontend/views/InputEmailPage.scala.html, conf/messages, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/ClaimEoriFormProviderSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/forms/EmailFormProviderSpec.scala
* email validation revised to include error messages for the following cases
* email not entered
* email too long
* email not in valid format
* factored out the email forms into separate form providers with dedicated tests
* simplified form providers by providing a common form method in the trait
* added messages
* other minor refactoring
=> ESC-755 revise email validation adding further error cases

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityController.scala
* A new user hitting the service for the first time arrives at the eori check page once they're enrolled. This creates some default state which was invalid, causing a redirect loop.
* This has been fixed by providing answers for both kickout pages, thus allowing the 'get first empty' logic to return the next page in the sequence correcty should the user navigate away from the eori check page without submitting it
=> ESC-825 ensure the saved EligiblityJourney state is valid to prevent redirect loops

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidies.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/models/UndertakingSubsidiesSpec.scala
* fixed a bug where there `isRemoved` state was not being checked when handling a remove request
* added `findNonHmrcSubsidy` method to UndertakingSubsidies which only matches on subsidies that are not removed and added tests
=> ESC-828 ensure repeated form submission cannot create a duplicate removed entry

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/types/package.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SubsidyControllerSpec.scala
* added in validation of the result of converting GBP to EUR to ensure the EUR amount does not exceed the maximum allowed value - if it does the `tooBig` form error will be shown
* added / revised tests
* other minor tidying
=> ESC-793 validate converted GBP amounts to ensure max value is not exceeded

app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailSendResult.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/EmailType.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/models/email/RetrieveEmailResponse.scala, project/AppDependencies.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/BecomeLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/EligibilityControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/NoClaimNotificationControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/SelectNewLeadControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala
* removed `ai.x.play-json-extensions` since it's not needed (we don't serialise the email enums)
* redefined the email enums using `enumeratum` for consistency
* bumped the hmrc play library versions to pull in the latest play version
* updated tests to set the correct request method now this is being validated
=> ESC-835 bump play versions and remove unnecessary play json extensions

app/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountController.scala, app/uk/gov/hmrc/eusubsidycompliancefrontend/util/ReportReminderHelpers.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/AccountControllerSpec.scala
Clean up the account controller so we don't duplicate the 90 day logic. Also simplified the code and the tests, removing a redundant time provider call, and simplifying the booleans used in some of the test methods.
=> ESC-850 - remove duplicate 90 logic from account controller

app/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmationPage.scala.html, conf/logback-test.xml, conf/messages, project/plugins.sbt, test/uk/gov/hmrc/eusubsidycompliancefrontend/controllers/UndertakingControllerSpec.scala, test/uk/gov/hmrc/eusubsidycompliancefrontend/views/ConfirmationPageSpec.scala
The content checks in this service are currently happening in the controller unit tests which is not great. For the relevant page here I've created a separate view spec to be more in line with our other services and better unit testing practice, and removed the content checks (aside from title) from the controller spec.
Also updated logback-text.xml to reduce noisy irrelevant logs in unit tests
=> DDCYLS-4779 Add exit survey to confirmation page
